name: CI
on:
  push:
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest]
        swift: [5.5, swift-DEVELOPMENT-SNAPSHOT-2022-01-09-a, swift-5.6-DEVELOPMENT-SNAPSHOT-2022-01-09-a]
        include:
          - swift: 5.5
            expected-version-string: "Swift version 5.5 (swift-5.5-RELEASE)"
          - swift: swift-DEVELOPMENT-SNAPSHOT-2022-01-09-a
            expected-version-string: "Swift version 5.6-dev (LLVM 7b20e61dd04138a, Swift 9438cf6b2e83c5f)"
          - swift: swift-5.6-DEVELOPMENT-SNAPSHOT-2022-01-09-a
            expected-version-string: "Swift version 5.6-dev (LLVM 143f1389db63309, Swift 00f7685e0968cbb)"
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Swift
      uses: ./
      with:
        version: ${{ matrix.swift }}

    - name: Print Swift Version
      run: swift --version

    - name: Check Swift Version
      run: |
        set -e
        swift --version | grep "${{ matrix.expected-version-string }}"
